language: php
php:
  - 5.5
  - 5.4
  - 5.3

services:
  - memcached

before_script:
  - mysql -e 'create database ecom;'

script:
  - php index.php
  - phpunit --no-globals-backup --static-backup --colors --bootstrap ./tests/_bootstrap.php ./tests/
