language: php
php:
  - 5.5
  - 5.4
  - 5.3

services:
  - memcached

before_script:
  - mysql -e 'create database ecom;'
  - mysql -e "CREATE USER 'test'@'127.0.0.1' IDENTIFIED BY 'p4ssW0rD!';"
  - mysql -e "GRANT USAGE ON *.* TO  'test'@'127.0.0.1' IDENTIFIED BY 'p4ssW0rD!' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;"
  - mysql -e "GRANT ALL PRIVILEGES ON  `ecom`.* TO 'test'@'127.0.0.1';"

script:
  #- php index.php
  - phpunit --no-globals-backup --static-backup --colors --bootstrap ./tests/_bootstrap.php ./tests/
